version: "1"

services:
  web:
    image: nikolavilar/iis-server:latest
    environment:
      MLFLOW_TRACKING_PASSWORD: ${MLFLOW_TRACKING_PASSWORD}
      MLFLOW_TRACKING_URI: ${MLFLOW_TRACKING_URI}
      MLFLOW_TRACKING_USERNAME: ${MLFLOW_TRACKING_USERNAME}
      MONGO_URI: ${MONGO_URI}
    ports:
      - "5000:5000"
    restart: always
  frontend:
    image: nikolavilar/iis-client:latest
    ports:
      - "4200:4200"
    restart: always