version: "1"

services:
  server:
    build:
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: always
    networks:
      mynet:
        ipv4_address: 172.28.1.2 

  client:
    build:
      context: ./src/client
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    restart: always
    networks:
      mynet:
        ipv4_address: 172.28.1.3

networks:
  mynet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16