name: Service Test

on:
  push:
    branches:
      - main

jobs:
  install_deps:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup poetry
        run: pip install poetry

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9.10"
          cache: poetry

      - name: Install deps
        run: |
          poetry install

  api_test:
    runs-on: ubuntu-20.04
    needs: install_deps
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup poetry
        run: pip install poetry

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9.10"
          cache: poetry

      - name: Setup git config
        run: |
          git config --global user.email "nikola.vilar@student.um.si"
          git config --global user.name "Nikola Vilar"

      - uses: iterative/setup-dvc@v1
      - name: Setup Dagshub
        run: |
          dvc remote modify origin --local access_key_id ${{ secrets.DAGSHUB_ACCESS_KEY_ID }}
          dvc remote modify origin --local secret_access_key ${{ secrets.DAGSHUB_SECRET_ACCESS_KEY}}

      - name: Pull changes
        run: |
          git pull
          dvc pull -r origin

      - name: Run pytest
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
          MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: poetry run pytest --reruns 3 --reruns-delay 5 tests/test_service.py
